vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        blog_images:
           uri_prefix: /images/blog
           upload_destination: '%kernel.project_dir%/public%blog_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false
